""" Quirks for list """,

quirk_list = [
        "Acid",
        "Acid Sweat",
        "Air Cannon",
        "Air Walk",
        "Air Wall",
        "All For One",
        "Amplivolt",
        "Anivoice",
        "Anthropomorph",
        "Arbor",
        "Assault Dust",
        "Attraction of Small Objects",
        "Barrier",
        "Bat",
        "Beams From His Eyes",
        "Beast",
        "Big Fist",
        "Big Horn",
        "Big Monkey",
        "Binging Ball",
        "Black",
        "Black Hole",
        "Blackwhip",
        "Blade-Tooth",
        "Blast",
        "Blazing Hair",
        "Blood Control",
        "Bloodcurdle",
        "Blueflame",
        "Body Bulk",
        "Body Morph",
        "Bombify",
        "Boomerang",
        "Brainwashing",
        "Bristle",
        "Brown Bear",
        "Bruiser",
        "Bubble",
        "Bull Head",
        "Bullet Laser",
        "Burst",
        "Cell Activation",
        "Cemedine",
        "Cement",
        "Centipede",
        "Chameleon",
        "Charging Muscles",
        "Chart",
        "Chest Hair",
        "Chimera",
        "Chronostasis",
        "Clean Bubbler",
        "Cleaning",
        "Clones",
        "Cloud",
        "Comic",
        "Compress",
        "Confession",
        "Control Horn",
        "Copy",
        "Cow",
        "Creation",
        "Crystallize",
        "Curse",
        "Danger Sense",
        "Dark Shadow",
        "Decay",
        "Despot",
        "Diesel Engine",
        "Dog",
        "Double",
        "Dragon",
        "Dragon Breath",
        "Dupli-Arms",
        "Dust",
        "Eagle",
        "Earphone Jack",
        "Earth Flow",
        "Eel",
        "Elasticity",
        "Electric Charge",
        "Electric Eel",
        "Electricity Generation",
        "Electrification",
        "Electromagnetic Bullets",
        "Endurance",
        "Energy Saver",
        "Energy Suck",
        "Engine",
        "Erasure",
        "Eruption",
        "Explosion",
        "Extend-o-Hair",
        "Extra Arms",
        "Fa Jin",
        "Fan",
        "Fat Absorption",
        "Fiber Master",
        "Fierce Gains",
        "Fierce Wings",
        "Fire Cracker",
        "Flash Bang Sweat",
        "Flight",
        "Float",
        "Fly Swatter",
        "Flying Squirrel",
        "Foldabody",
        "Food",
        "Forced Quirk Activation",
        "Foresight",
        "Free Walker",
        "Frog",
        "Frost",
        "Gale Gale",
        "Gas",
        "Gatling",
        "Gearshift",
        "Gecko",
        "Gigantic Spinning Flying Turtle",
        "Gigantification",
        "Glamour",
        "Glide and Slide",
        "Glycerin",
        "Good Ear",
        "Grasshopper",
        "Gyrate",
        "Hair Control",
        "Hair-Raiser",
        "Half-Cold Half-Hot",
        "Hardening",
        "Hardflame Fan",
        "Heal",
        "Heavy Payload",
        "Helical Scythe",
        "Hellflame",
        "High Spec",
        "Hologram",
        "Homing",
        "Horn Cannon",
        "Hula Hoop",
        "Hydra",
        "Hypertrophy",
        "Ice Manipulation",
        "Ignition",
        "Impact Recoil",
        "Incite",
        "Infrared",
        "Invisibility",
        "IQ",
        "Iron Ball",
        "Iron Claws",
        "Iron Club",
        "Jet",
        "Kaiju",
        "King Slam",
        "Landmine",
        "Larceny",
        "Laser",
        "Leafipulation",
        "Leap",
        "Life Force",
        "Lion",
        "Liquification",
        "Lizard",
        "Lizard Tail Splitter",
        "Lock Down",
        "Longbow",
        "Longleg",
        "Love",
        "Magic",
        "Magnetism",
        "Manifest",
        "Mantis",
        "Meatball",
        "Metal Manipulation",
        "Mimicry",
        "Mind Reaper",
        "Mole",
        "Monster Cat",
        "Muddied",
        "Multiplier",
        "Mummification",
        "Muscle Augmentation",
        "Muscle Expansion",
        "Mushroom",
        "Mutant Bovini",
        "Navel Laser",
        "New Order",
        "Octopus",
        "Octopus",
        "One For All",
        "Orcinus",
        "Outburst",
        "Overclock"]
